export const BOOKS_GET = 'BOOKS_GET';
export const BOOKS_GET_SUCCESSFULL = 'BOOKS_GET_SUCCESSFULL';
export const BOOKS_GET_FAILURE = 'BOOKS_GET_FAILURE';
export const BOOKS_GET_REQUEST = 'BOOKS_GET_REQUEST';

export const MOVIES_GET = 'MOVIES_GET';
export const MOVIES_GET_SUCCESSFULL = 'MOVIES_GET_SUCCESSFULL';
export const MOVIES_GET_FAILURE = 'MOVIES_GET_FAILURE';
export const MOVIES_GET_REQUEST = 'MOVIES_GET_REQUEST';